### ISSUE TITLE
Refactoring the builders generator methods

### ISSUE THREAD

**Issue by olivernybroe** [uruloke/LaraCalendar#8]
In the [EventBuilder](https://github.com/uruloke/LaraCalendar/blob/master/src/EventBuilder.php), we have two methods which have a lot of duplications.
[EventBuilder#getEventsBetween ](https://github.com/uruloke/LaraCalendar/blob/master/src/EventBuilder.php#L102)
[EventBuilder#getNextEvents](https://github.com/uruloke/LaraCalendar/blob/master/src/EventBuilder.php#L139) 
This needs to be cleaned up, as the implementation is mostly the same.

**Comment by lexf** [comment]
I can help with this.
